---
title: "Drought Bangladesh"
output: html_document
date: '2022-09-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Attach packages

```{r packages}
library("plyr")                     # Load plyr package
library("dplyr")
library("readr")                    # Load readr package
library("ncdf4")                    # package for netcdf manipulation
library("raster")                   # package for raster manipulation
#library("rgdal")                    # package for geospatial analysis
library("ggplot2")                  # package for plotting
library("haven")                    # Load dta files
library("dplyr")                    # Load dplyr package
library("foreign")                  # Export dta files
library("geosphere")                # Find the geographical distance 
library("rworldmap")                # Mapping country boundaries                  
library("leaflet")                  # Interactive maps
library("htmlwidgets")              # HTML widgets
library("RColorBrewer")             # Nice colours
library("scales")                   # Scales for graphs
library("sf")                       # working with shapefiles
#library("rgeos")
library("SPEI")                     # SPEI construction
library("vctrs")                    # Vector operations
```



